### ISSUE TITLE
missing example: droplet crown sim

### ISSUE THREAD

**Issue by chriscamacho** [ProfJski/RayLib-Examples#1]
neat examples, but with tongue in cheek, while chancing my arm...

Some kind of simulation that could show this effect would look amazing !

the ability to change droplet size and speed as well as slo-mo would be nice! 

https://www.youtube.com/results?search_query=milk+droplet+coronet

**Comment by ProfJski** [comment]
Thanks!  Slow-motion can be easily achieved by changing a single line in the code.  Look for the line with command `SetTargetFPS()` and supply whatever argument you wish.  For example `SetTargetFPS(10)` will give you 10 FPS, automatically slowing down the render loop to meet the desired speed.

To render the milk-droplet would be awesome.  Unfortunately, it would take a require a very different and much more complicated approach.  I've been playing with various ways to render to the Navier-Stokes equation in a more simplistic fashion, but nothing exciting to share so far.  In any case, it would be a totally different program.
