### ISSUE TITLE
Use raylib include files not installed by raylib

### ISSUE THREAD

**Issue by jimcruse** [ProfJski/RayLib-Examples#2]
The code uses raymath.h and raygui.h and r1gl.h which are not installed by the makefile from the git zip raylib zip
The only header file installed is raylib.h

**Comment by raysan5** [comment]
@jimcruse I think it's up to de "advance" user to pick required headers.

**Comment by jimcruse** [comment]
I agree but I think that is true, but you copy raylib.h why not raymath.h
and raygui.h .....

**Comment by jimcruse** [comment]
Sorry, you are correct

**Comment by ProfJski** [comment]
I added a note to say that demos with a GUI need [RayGUI](https://github.com/raysan5/raygui) as well as RayLib.  RayGUI is very easy to install -- it's header-only.
